version: '3.1'
services:
  python-app:
    build: .
    ports:
      - 9090:9090
    depends_on:
      - clickhouse

  clickhouse:
    image: yandex/clickhouse-server
    container_name: some-clickhouse-server
    ports:
      - 8123:8123
      - 9000:9000
    volumes:
      - ./clickhouse_data:/var/lib/clickhouse
    ulimits:
      nproc: 65535
      nofile:
        soft: 262144
        hard: 262144
